# Generated by Django 6.0.5 on 2026-05-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'permissions': [('can_manage_customers', 'Can create and provision customer profiles')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-interaction_date'], 'permissions': [('can_log_interactions', 'Can log and record customer interactions')], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
    ]
