# Generated by Django 6.0.5 on 2026-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learners',
            field=models.ManyToManyField(to='onlinecourse.learner'),
        ),
    ]
